const state={data:null,language:"en",searchQuery:"",filter:"all",favorites:new Set()};
const LANGUAGES=["ru","en","th"],FILTERS=["all","popular","vegetarian","vegan","spicy","new"],DEFAULT_LANGUAGE="en";
const $=s=>document.querySelector(s);
function translate(v){if(v==null)return"";if(typeof v==="string")return v;return v[state.language]??v[DEFAULT_LANGUAGE]??v.ru??v.en??v.th??""}
function escapeHTML(v){return String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;")}
function ui(k){return state.data?.ui?.[k]?translate(state.data.ui[k]):k}
function formatPrice(price){if(price&&typeof price==="object")return Object.entries(price).map(([s,v])=>`${escapeHTML(translate(state.data.ui?.sizes?.[s]??s))} ${escapeHTML(v)} ${escapeHTML(state.data.currency||"")}`).join(" · ");return price==null?"":`${escapeHTML(price)} ${escapeHTML(state.data.currency||"")}`.trim()}
function loadLocalStorage(){const l=localStorage.getItem("menuLanguage");if(l&&LANGUAGES.includes(l))state.language=l;try{state.favorites=new Set(JSON.parse(localStorage.getItem("menuFavorites")||"[]").map(String))}catch{state.favorites=new Set()}}
function detectLanguage(){const l=(navigator.language||"").toLowerCase();return l.startsWith("th")?"th":l.startsWith("ru")?"ru":state.data.defaultLanguage||DEFAULT_LANGUAGE}
function dishIsVisible(d){if(d.available===false)return false;const q=state.searchQuery.trim().toLowerCase();if(q&&!`${translate(d.name)} ${translate(d.description)}`.toLowerCase().includes(q))return false;return state.filter==="all"||d[state.filter]===true}
function renderHeader(){const r=state.data.restaurant;document.documentElement.lang=state.language;document.title=`${translate(r.name)} — ${ui("menu")}`;$("#site-header").innerHTML=`<div class="header-top"><div class="brand">${r.logo?`<img class="logo" src="${escapeHTML(r.logo)}" alt="${escapeHTML(translate(r.name))}">`:""}<div class="brand-text"><h1 class="brand-name">${escapeHTML(translate(r.name))}</h1><p class="brand-description">${escapeHTML(translate(r.description))}</p></div></div><div class="lang-switch">${LANGUAGES.map(l=>`<button type="button" class="lang-button ${state.language===l?"active":""}" data-language="${l}">${l.toUpperCase()}</button>`).join("")}</div></div>`;document.querySelectorAll("[data-language]").forEach(b=>b.onclick=()=>{state.language=b.dataset.language;localStorage.setItem("menuLanguage",state.language);render()})}
function renderToolbar(){const filters=FILTERS.map(f=>`<button type="button" class="filter-button ${state.filter===f?"active":""}" data-filter="${f}">${escapeHTML(ui(f))}</button>`).join("");$("#toolbar").innerHTML=`<div class="search-container"><input id="search-input" class="search-input" type="search" value="${escapeHTML(state.searchQuery)}" placeholder="${escapeHTML(ui("search"))}" aria-label="${escapeHTML(ui("search"))}"></div><div class="filters">${filters}</div>`;$("#search-input").oninput=e=>{state.searchQuery=e.target.value;renderMenu()};document.querySelectorAll("[data-filter]").forEach(b=>b.onclick=()=>{state.filter=b.dataset.filter;renderToolbar();renderMenu()})}
function renderCategories(){$("#category-nav").innerHTML=(state.data.categories||[]).map(c=>`<a class="category-link" href="#category-${escapeHTML(c.id)}">${escapeHTML(translate(c.name))}</a>`).join("")}
function renderTags(d){const tags=[];if(d.popular)tags.push(ui("popular"));if(d.new)tags.push(ui("new"));if(d.vegetarian)tags.push(ui("vegetarian"));if(d.vegan)tags.push(ui("vegan"));if(d.spicy)tags.push(ui("spicy"));return tags.length?`<div class="dish-tags">${tags.map(t=>`<span class="dish-tag">${escapeHTML(t)}</span>`).join("")}</div>`:""}
function renderDish(d){const fav=state.favorites.has(String(d.id));return `<article class="dish-card" data-dish-id="${escapeHTML(d.id)}"><img class="dish-image" loading="lazy" src="${escapeHTML(d.image||"images/placeholder.svg")}" alt="${escapeHTML(translate(d.name))}" onerror="this.onerror=null;this.src='images/placeholder.svg'"><div class="dish-content"><div class="dish-header"><h3 class="dish-name">${escapeHTML(translate(d.name))}</h3><button type="button" class="favorite-button ${fav?"active":""}" data-favorite="${escapeHTML(d.id)}" aria-label="${fav?"Remove from favorites":"Add to favorites"}">${fav?"♥":"♡"}</button></div><div class="dish-price">${formatPrice(d.price)}</div>${translate(d.description)?`<p class="dish-description">${escapeHTML(translate(d.description))}</p>`:""}${renderTags(d)}</div></article>`}
function renderMenu(){let total=0;const html=(state.data.categories||[]).map(c=>{const dishes=(c.dishes||[]).filter(dishIsVisible);if(!dishes.length)return"";total+=dishes.length;return `<section class="category" id="category-${escapeHTML(c.id)}"><h2 class="category-title">${escapeHTML(translate(c.name))}</h2>${c.description?`<p class="category-description">${escapeHTML(translate(c.description))}</p>`:""}<div class="dishes">${dishes.map(renderDish).join("")}</div></section>`}).join("");$("#menu").innerHTML=total?html:`<div class="empty-state">${escapeHTML(ui("nothingFound"))}</div>`;document.querySelectorAll("[data-favorite]").forEach(b=>b.onclick=()=>{const id=String(b.dataset.favorite);state.favorites.has(id)?state.favorites.delete(id):state.favorites.add(id);localStorage.setItem("menuFavorites",JSON.stringify([...state.favorites]));renderMenu()})}
function renderFooter(){const r=state.data.restaurant,links=[];if(r.phone)links.push({label:ui("phone"),url:`tel:${r.phone}`});if(r.maps)links.push({label:ui("maps"),url:r.maps});if(r.website)links.push({label:ui("website"),url:r.website});if(r.facebook)links.push({label:ui("facebook"),url:r.facebook});if(r.instagram)links.push({label:ui("instagram"),url:r.instagram});if(r.line)links.push({label:ui("line"),url:r.line});$("#site-footer").innerHTML=`<div class="footer-name">${escapeHTML(translate(r.name))}</div>${r.address?`<div class="footer-row">${escapeHTML(translate(r.address))}</div>`:""}${r.hours?`<div class="footer-row">${escapeHTML(translate(r.hours))}</div>`:""}${links.length?`<div class="footer-links">${links.map(x=>`<a class="footer-link" href="${escapeHTML(x.url)}" target="${x.url.startsWith("tel:")?"_self":"_blank"}" rel="noopener noreferrer">${escapeHTML(x.label)}</a>`).join("")}</div>`:""}`}
function render(){renderHeader();renderToolbar();renderCategories();renderMenu();renderFooter()}
async function loadMenu(){try{const r=await fetch("menu.json",{cache:"no-store"});if(!r.ok)throw new Error(`HTTP ${r.status}`);state.data=await r.json();loadLocalStorage();if(!localStorage.getItem("menuLanguage"))state.language=detectLanguage();render()}catch(e){console.error(e);$("#menu").innerHTML=`<div class="error-state">Unable to load the menu.<br><br>Please check <strong>menu.json</strong>.</div>`}}
loadMenu();
